### ISSUE TITLE
ECAM displays remain static when location is changed

### ISSUE THREAD

**Issue by bob755** [it0uchpods/IDG-A32X#88] opened 2017-11-11 01:12 UTC
Steps to Reproduce:
1. FG started with default location.
2. Location changed via menu Location -> Select Airport
3. ECAM displays do not update.  displayed values remain static.  On one occasion both displayed were blank after a location change.
This happens sytematically.

After a  reset (File -> Reset ), the displays refresh correctly .

**Comment by it0uchpods** [comment] 2017-11-11 01:45
Please use our template in the future.

I need more complete steps, following what you said, the displays would be blank due to no power, so I cannot reproduce that until you provide more complete steps.... 

Kind Regards,
Josh

**Comment by bob755** [comment] 2017-11-11 08:36
### Current Behavior

ECAM displays are blank after engine startup if aircraft location is changed.

### Steps to Reproduce

1. Load FG. Default aircraft: Airbus A320-251N. Default location: LFMT

1. Menu : Loacation -> Select Airport

1. Go to LFMN

1. Menu; ADG-32X-> Aircraft Config -> Ready for Taxi

![blank ecam](https://user-images.githubusercontent.com/33560670/32687744-9e9f162e-c6c3-11e7-9aa0-bd6a75fe1a45.PNG)

**Comment by Wecsje** [comment] 2017-11-11 10:47
@bob755 Do you want me to re-open the issue and look into it, or is the problem already fixed?

C.

**Comment by bob755** [comment] 2017-11-11 10:53
Please re-open the issue. Let me know if you need additional information.  
Thanks.

**Comment by Wecsje** [comment] 2017-11-11 10:58
Ok, we will take a look.

**Comment by Wecsje** [comment] 2017-11-11 11:05
Bug confirmed. I would suggest you however set your airport in the launcher, then this problem won't happen. We will take a look at it, but it might take some time, as it is not our primary concern.

C.

**Comment by it0uchpods** [comment] 2017-11-11 13:49
Thanks, that's all I needed, will look into it in a few hours.

**Comment by bob755** [comment] 2017-11-11 15:36
Yes I usually set the airport in the launcher so it's not a high priority. 
Thanks.

**Comment by it0uchpods** [comment] 2017-11-11 16:21
Please let us close the issue until it's resolved -- thx

Bug confirmed. The canvas itself is working, as clicking the displays, it works. But it doesn't get mapped to the object.

So, it is a bug, and I will fix it today.

**Comment by it0uchpods** [comment] 2017-11-11 16:25
Actually -- this is an FG problem. It seems to stop nasal timers, and JSBsim from updating properly. After doing some testing, I found most of my systems logic stopped working properly.

So, I suggest just selecting it from the runway. I will look into a way to detect these changes, and force the systems to reset.

Kind Regards,
Josh

**Closed by it0uchpods** 2017-11-11 16:25 UTC
Labels: bug
