### ISSUE TITLE
Starting causes segfault

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#71] opened 2017-10-28 19:36 UTC
### Expected Behavior
Starting FG

### Current Behavior
FG segfaults sometimes (only happens with this plane, others work allways)

**Comment by Wecsje** [comment] 2017-10-28 19:47
Check that the aircraft is located on a disk that has both read/write access. Please post the log file, and describe the error in more detail. Segfaults are probably not because of a bug in the aircraft, but we would like to further investigate this.

Regards,

Charlie (Wecsje)

**Comment by it0uchpods** [comment] 2017-10-28 21:27
Closing this because it's (likely) not a problem with the IDG-A32X. Please post your full system specs. Segfaults are not usually caused by the airplane. If it comes to the fact where the IDG-A32X is the cause, I will reopen this.

**Closed by it0uchpods** 2017-10-28 21:27 UTC
Labels: help wanted
