### ISSUE TITLE
Wing Views: zooming teleports view

### ISSUE THREAD

**Issue by legoboyvdlp** [it0uchpods/IDG-A32X#41] opened 2018-09-21 16:37 UTC
### Expected Behavior
View does not teleport 30m in front of aircraft when you use x key in wing views

### Current Behavior
![image](https://user-images.githubusercontent.com/10434911/45893957-dfc0e300-bdc4-11e8-8b19-eb84bd29af2a.png)

### Steps to Reproduce
1. In wing view, press x

**Comment by merspieler** [comment] 2018-09-24 10:55
I don't experiense this in any of the 3 wing views. In all it works fine.

**Comment by it0uchpods** [comment] 2018-09-28 18:51
I don't either.

**Comment by legoboyvdlp** [comment] 2018-09-28 22:56
I had this in the f16 as well. It definitely was occuring.

**Comment by legoboyvdlp** [comment] 2018-09-28 22:56
Let me try and reproduce it again

**Comment by it0uchpods** [comment] 2018-09-28 22:59
Check discord, f16 server please.

**Comment by it0uchpods** [comment] 2018-09-28 23:00
Just tried, nothing wrong.

**Comment by it0uchpods** [comment] 2018-09-28 23:06
Leto can't reproduce it either.

Lets leave this closed until it is reproducable.

**Comment by it0uchpods** [comment] 2018-10-13 18:38
fixed in 7a3e31c5
thx lego.
Josh

**Closed by it0uchpods** 2018-10-13 18:38 UTC
Labels: bug, confirmed

**Comment by legoboyvdlp** [comment] 2018-10-13 20:02
Awesome :smile: Thanks to you!

**Comment by it0uchpods** [comment] 2018-10-13 20:05
thx for reporting it -- even if it took me a while to reproduce it ;)
