### ISSUE TITLE
Plane doesn't show up and INSTALL file

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#68] opened 2017-10-22 00:29 UTC
It looks like #60 but I've double checked the directory name.

You can find the full log here: https://privatebin.net/?cbbd37040462c1ba#dZ29F8uVQFwiQsP2lAj2ENqh1rufn3x2FXHcXPqESr4=

OS: Debian 9
FG version: 2016.4.4 (from package manager)

**Comment by it0uchpods** [comment] 2017-10-22 00:34
Please use our issue template in the future...

It looks like it can't find anything the plane needs to load. 

I've heard of an issue where linux FGFS doesn't recognize the "Aircraft" path starter, like the Windows/Mac ones do. Try putting the aircraft in a folder called Aircraft, and making that folder a aircraft location. 

Kind Regards,
Josh

**Comment by merspieler** [comment] 2017-10-23 12:43
I've checked the path, as well the` /usr/share` and the `~/.fgfs` and added the directorys to the aircraft path, with the same result.

Then I've tryed the same version on windows with the same problem.

After an update to the latest version on win, though it shows at least the splash screen.

I might try the git clone command instead of the zip download to try diffrent commits.

Btw. it might be a good idea to make a release which is stable.

**Comment by it0uchpods** [comment] 2017-10-23 13:01
Hi, that is strange. Are you able to send screenshots that might give more information?

If it happens on windows also, you are probably installing it wrong. Make sure you remove -master, and make sure inside the IDG-A32X folder is the files, instead of another IDG-A32X folder first. (Like WinRAR does)

Stable will the V1.0. We are in beta. By V1.0, everything will be ready.

Kind Regards,
Josh

**Comment by it0uchpods** [comment] 2017-10-23 14:20
Hi
I just took another look at the log, and I found the problem.

The aircraft hasn't been called A320Family for monthes now. It's now called "IDG-A32X" (no quotes)

Also, we require 2017.3.0 or later, since we use the new flightplan system in that version. Any prior version will cause a mismatch error.

I'm closing this issue now, since this issue is not caused by the aircraft.

Kind Regards,
Josh

**Comment by merspieler** [comment] 2017-10-23 16:24
I'll try it with the othern name and the latest release.

You might add an `INSTALL` file with dependencies and install instructions to not let others run into this kind of problems.

**Comment by it0uchpods** [comment] 2017-10-23 16:28
Hi
You said you knew to remove master, which is fairly common knowledge for github. If cloning, its even easier.

The fact the folder and repo name changed and you didn't notice is not our problem, sorry!

Kind Regards,
Josh

**Comment by merspieler** [comment] 2017-10-23 16:30
Sure... but I've ment as well the minimum FG version

**Comment by it0uchpods** [comment] 2017-10-23 16:31
The plane alerts you of that when you start FGFS, but I guess I could add that to the readme. Its also stated on the wiki.

Kind Regards,
Josh

**Comment by merspieler** [comment] 2017-10-24 09:15
I can confirm, that it was kinda my fault.

With renamig the directory correctly it works now (Tested under win, under linux i haven't installed the latest version yet).

If wanted, I could contribute the `INSTALL`  file.

**Comment by Wecsje** [comment] 2017-10-24 12:19
Hi,

That would be very nice!
Please fork the repo, make/contribute, and then submit them via a pull request.

Regards,

Charlie (Wecsje)

**Closed** 2017-10-24 13:52 UTC
Labels: enhancement, help wanted
